#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6 on Fri Nov  2 11:44:36 2007

import wx
import LadFrame

class Lad(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        main_window = LadFrame.LadFrame(None, -1, "")
        self.SetTopWindow(main_window)
        main_window.Show()
        return 1

# end of class Lad

if __name__ == "__main__":
    lad = Lad(0)
    lad.TopWindow.canvas.InitArtist()
    lad.TopWindow.InitNotebook()
    lad.TopWindow.InitShell()
    lad.MainLoop()
